In [1]:
import sys
import os

import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold

In [53]:
df = pd.read_csv('./df_kaggle.csv')
df

Unnamed: 0  Unnamed: 0.1  \
0              0             0   
1              1             1   
2              2             2   
3              3             3   
4              4             4   
...          ...           ...   
4216        4216          3891   
4217        4217          3892   
4218        4218          3893   
4219        4219          3894   
4220        4220          3895   

                                                   path            x  \
0                ../input/pothole-end/train/ds1_511.jpg  1361.945996   
1                ../input/pothole-end/train/ds1_511.jpg   987.311850   
2               ../input/pothole-end/train/ds1_1845.jpg  1088.784657   
3               ../input/pothole-end/train/ds1_1924.jpg   814.868102   
4               ../input/pothole-end/train/ds1_1952.jpg  1375.621803   
...                                                 ...          ...   
4216  ../input/road-pothole-images-for-pothole-detec...   242.000000   
4217  ../input/road-pothole-images-for-pothole-detec...  2674.000000   
4218  ../input/road-pothole-images-for-pothole-detec...  1902.000000   
4219  ../input/road-pothole-images-for-pothole-detec...  1898.000000   
4220  ../input/road-pothole-images-for-pothole-detec...  2214.000000   

                y           w          h  
0      953.269770   63.439024  77.530650  
1      924.494335   89.149211  42.632578  
2      792.205742   60.434724  27.698565  
3      837.851675   77.662180  16.502392  
4      892.110048  138.819650  56.980861  
...           ...         ...        ...  
4216  1642.000000  156.000000  42.000000  
4217  1722.000000  156.000000  44.000000  
4218  1614.000000  118.000000  52.000000  
4219  1550.000000   74.000000  30.000000  
4220  1626.000000  158.000000  80.000000  

[4221 rows x 7 columns]

In [54]:
df.drop(columns=['Unnamed: 0'], inplace=True)
df

Unnamed: 0.1                                               path  \
0                0             ../input/pothole-end/train/ds1_511.jpg   
1                1             ../input/pothole-end/train/ds1_511.jpg   
2                2            ../input/pothole-end/train/ds1_1845.jpg   
3                3            ../input/pothole-end/train/ds1_1924.jpg   
4                4            ../input/pothole-end/train/ds1_1952.jpg   
...            ...                                                ...   
4216          3891  ../input/road-pothole-images-for-pothole-detec...   
4217          3892  ../input/road-pothole-images-for-pothole-detec...   
4218          3893  ../input/road-pothole-images-for-pothole-detec...   
4219          3894  ../input/road-pothole-images-for-pothole-detec...   
4220          3895  ../input/road-pothole-images-for-pothole-detec...   

                x            y           w          h  
0     1361.945996   953.269770   63.439024  77.530650  
1      987.311850   924.494335   89.149211  42.632578  
2     1088.784657   792.205742   60.434724  27.698565  
3      814.868102   837.851675   77.662180  16.502392  
4     1375.621803   892.110048  138.819650  56.980861  
...           ...          ...         ...        ...  
4216   242.000000  1642.000000  156.000000  42.000000  
4217  2674.000000  1722.000000  156.000000  44.000000  
4218  1902.000000  1614.000000  118.000000  52.000000  
4219  1898.000000  1550.000000   74.000000  30.000000  
4220  2214.000000  1626.000000  158.000000  80.000000  

[4221 rows x 6 columns]

In [55]:
df['label']= 1
df

Unnamed: 0.1                                               path  \
0                0             ../input/pothole-end/train/ds1_511.jpg   
1                1             ../input/pothole-end/train/ds1_511.jpg   
2                2            ../input/pothole-end/train/ds1_1845.jpg   
3                3            ../input/pothole-end/train/ds1_1924.jpg   
4                4            ../input/pothole-end/train/ds1_1952.jpg   
...            ...                                                ...   
4216          3891  ../input/road-pothole-images-for-pothole-detec...   
4217          3892  ../input/road-pothole-images-for-pothole-detec...   
4218          3893  ../input/road-pothole-images-for-pothole-detec...   
4219          3894  ../input/road-pothole-images-for-pothole-detec...   
4220          3895  ../input/road-pothole-images-for-pothole-detec...   

                x            y           w          h  label  
0     1361.945996   953.269770   63.439024  77.530650      1  
1      987.311850   924.494335   89.149211  42.632578      1  
2     1088.784657   792.205742   60.434724  27.698565      1  
3      814.868102   837.851675   77.662180  16.502392      1  
4     1375.621803   892.110048  138.819650  56.980861      1  
...           ...          ...         ...        ...    ...  
4216   242.000000  1642.000000  156.000000  42.000000      1  
4217  2674.000000  1722.000000  156.000000  44.000000      1  
4218  1902.000000  1614.000000  118.000000  52.000000      1  
4219  1898.000000  1550.000000   74.000000  30.000000      1  
4220  2214.000000  1626.000000  158.000000  80.000000      1  

[4221 rows x 7 columns]

In [56]:
# def revise_path(p):
#     folder = p.split('/')[2].strip()
#     file_name = p.split('/')[3].strip()
#     new_p = '/' + folder + '/' + file_name
#     return new_p 


# df['path'] = df['path'].apply(lambda x: revise_path(x))
# df

In [57]:
# df['x'] = df['x'].apply(lambda x: int(x))
# df['y'] = df['y'].apply(lambda x: int(x))
# df['w'] = df['w'].apply(lambda x: int(x))
# df['h'] = df['h'].apply(lambda x: int(x))

# df

In [58]:
# df['x'] = df['x'].apply(lambda x: float(x))
# df['y'] = df['y'].apply(lambda x: float(x))
# df['w'] = df['w'].apply(lambda x: float(x))
# df['h'] = df['h'].apply(lambda x: float(x))

# df

In [59]:
# df.to_csv('train_dataset2.csv')

In [60]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

df_folds = df[['path']].copy()
# 일단 박스 하나당 1이라는 index를 주어줌 (박스별로 나누기 위함)
df_folds.loc[:, 'bbox_count'] = 1

df_folds

path  bbox_count
0                ../input/pothole-end/train/ds1_511.jpg           1
1                ../input/pothole-end/train/ds1_511.jpg           1
2               ../input/pothole-end/train/ds1_1845.jpg           1
3               ../input/pothole-end/train/ds1_1924.jpg           1
4               ../input/pothole-end/train/ds1_1952.jpg           1
...                                                 ...         ...
4216  ../input/road-pothole-images-for-pothole-detec...           1
4217  ../input/road-pothole-images-for-pothole-detec...           1
4218  ../input/road-pothole-images-for-pothole-detec...           1
4219  ../input/road-pothole-images-for-pothole-detec...           1
4220  ../input/road-pothole-images-for-pothole-detec...           1

[4221 rows x 2 columns]

In [61]:
df_folds = df_folds.groupby('path').count()

df_folds

bbox_count
path                                                          
../input/pothole-end/train/ds1_10157.jpg                     1
../input/pothole-end/train/ds1_11292.jpg                     1
../input/pothole-end/train/ds1_13673.jpg                     1
../input/pothole-end/train/ds1_13825.jpg                     1
../input/pothole-end/train/ds1_13869.jpg                     1
...                                                        ...
../input/road-pothole-images-for-pothole-detect...           1
../input/road-pothole-images-for-pothole-detect...           2
../input/road-pothole-images-for-pothole-detect...           2
../input/road-pothole-images-for-pothole-detect...           3
../input/road-pothole-images-for-pothole-detect...           1

[1401 rows x 1 columns]

In [62]:
# df_folds에 label 축 생성
df_folds.loc[:, 'label'] = df[['path', 'label']].groupby('path').min()['label']

# df_folds['label'].unique()
df_folds

bbox_count  label
path                                                                 
../input/pothole-end/train/ds1_10157.jpg                     1      1
../input/pothole-end/train/ds1_11292.jpg                     1      1
../input/pothole-end/train/ds1_13673.jpg                     1      1
../input/pothole-end/train/ds1_13825.jpg                     1      1
../input/pothole-end/train/ds1_13869.jpg                     1      1
...                                                        ...    ...
../input/road-pothole-images-for-pothole-detect...           1      1
../input/road-pothole-images-for-pothole-detect...           2      1
../input/road-pothole-images-for-pothole-detect...           2      1
../input/road-pothole-images-for-pothole-detect...           3      1
../input/road-pothole-images-for-pothole-detect...           1      1

[1401 rows x 2 columns]

In [63]:
df_folds.bbox_count.describe()

count    1401.000000
mean        3.012848
std         2.996399
min         1.000000
25%         1.000000
50%         2.000000
75%         4.000000
max        22.000000
Name: bbox_count, dtype: float64

In [64]:
 df_folds['bbox_count'].apply(lambda x: f'_{x // 3}').values.astype(str)

array(['_0', '_0', '_0', ..., '_0', '_1', '_0'], dtype='<U2')

In [65]:
# df_folds에 stratify_group 축 생성

# bbox_count는 한 이미지 내에 있는 전체 box의 갯수
# 만약 한 이미지내에 box의 갯수가 지나치게 많은 경우 라벨링을 1_0, 1_1, 1_2 ... 로 이중 라벨링을 매겨서 세분화 한 뒤 학습
# 실제로 GWD에서는 한 이미지에 박스가 매우 많았음
df_folds.loc[:, 'stratify_group'] = np.char.add(
    df_folds['label'].values.astype(str),
    df_folds['bbox_count'].apply(lambda x: f'_{x // 3}').values.astype(str)
)

# df_folds['stratify_group'].unique()

df_folds

bbox_count  label  \
path                                                                    
../input/pothole-end/train/ds1_10157.jpg                     1      1   
../input/pothole-end/train/ds1_11292.jpg                     1      1   
../input/pothole-end/train/ds1_13673.jpg                     1      1   
../input/pothole-end/train/ds1_13825.jpg                     1      1   
../input/pothole-end/train/ds1_13869.jpg                     1      1   
...                                                        ...    ...   
../input/road-pothole-images-for-pothole-detect...           1      1   
../input/road-pothole-images-for-pothole-detect...           2      1   
../input/road-pothole-images-for-pothole-detect...           2      1   
../input/road-pothole-images-for-pothole-detect...           3      1   
../input/road-pothole-images-for-pothole-detect...           1      1   

                                                   stratify_group  
path                                                               
../input/pothole-end/train/ds1_10157.jpg                      1_0  
../input/pothole-end/train/ds1_11292.jpg                      1_0  
../input/pothole-end/train/ds1_13673.jpg                      1_0  
../input/pothole-end/train/ds1_13825.jpg                      1_0  
../input/pothole-end/train/ds1_13869.jpg                      1_0  
...                                                           ...  
../input/road-pothole-images-for-pothole-detect...            1_0  
../input/road-pothole-images-for-pothole-detect...            1_0  
../input/road-pothole-images-for-pothole-detect...            1_0  
../input/road-pothole-images-for-pothole-detect...            1_1  
../input/road-pothole-images-for-pothole-detect...            1_0  

[1401 rows x 3 columns]

In [66]:
# df_folds에 fold 축 생성
df_folds.loc[:, 'fold'] = 0

df_folds

bbox_count  label  \
path                                                                    
../input/pothole-end/train/ds1_10157.jpg                     1      1   
../input/pothole-end/train/ds1_11292.jpg                     1      1   
../input/pothole-end/train/ds1_13673.jpg                     1      1   
../input/pothole-end/train/ds1_13825.jpg                     1      1   
../input/pothole-end/train/ds1_13869.jpg                     1      1   
...                                                        ...    ...   
../input/road-pothole-images-for-pothole-detect...           1      1   
../input/road-pothole-images-for-pothole-detect...           2      1   
../input/road-pothole-images-for-pothole-detect...           2      1   
../input/road-pothole-images-for-pothole-detect...           3      1   
../input/road-pothole-images-for-pothole-detect...           1      1   

                                                   stratify_group  fold  
path                                                                     
../input/pothole-end/train/ds1_10157.jpg                      1_0     0  
../input/pothole-end/train/ds1_11292.jpg                      1_0     0  
../input/pothole-end/train/ds1_13673.jpg                      1_0     0  
../input/pothole-end/train/ds1_13825.jpg                      1_0     0  
../input/pothole-end/train/ds1_13869.jpg                      1_0     0  
...                                                           ...   ...  
../input/road-pothole-images-for-pothole-detect...            1_0     0  
../input/road-pothole-images-for-pothole-detect...            1_0     0  
../input/road-pothole-images-for-pothole-detect...            1_0     0  
../input/road-pothole-images-for-pothole-detect...            1_1     0  
../input/road-pothole-images-for-pothole-detect...            1_0     0  

[1401 rows x 4 columns]

In [67]:
folds = [(idxT,idxV) for i,(idxT,idxV) in enumerate(skf.split(np.arange(df_folds.shape[0]), df_folds['stratify_group']))]
for i in range(5):
    (idxT,idxV) = folds[i]
    
    print(idxT)

[   0    1    2 ... 1397 1398 1399]
[   2    5    6 ... 1398 1399 1400]
[   0    1    2 ... 1397 1399 1400]
[   0    1    2 ... 1398 1399 1400]
[   0    1    3 ... 1396 1398 1400]


/home/kerrykim/anaconda3/envs/skku/lib/python3.9/site-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


In [70]:
df_folds.to_csv('df_kaggle_fold.csv')

In [69]:
print(folds)

[(array([   0,    1,    2, ..., 1397, 1398, 1399]), array([   9,   15,   16,   20,   25,   26,   29,   31,   32,   34,   39,
         43,   45,   46,   47,   48,   67,   96,  102,  104,  106,  110,
        123,  134,  135,  140,  141,  143,  150,  151,  156,  161,  162,
        163,  168,  171,  177,  198,  200,  202,  210,  215,  228,  229,
        237,  239,  241,  254,  263,  268,  272,  273,  276,  277,  278,
        282,  290,  291,  292,  295,  300,  307,  314,  316,  318,  323,
        324,  328,  337,  341,  349,  350,  353,  356,  357,  362,  368,
        373,  379,  384,  387,  406,  412,  416,  417,  420,  421,  424,
        428,  432,  434,  441,  442,  445,  446,  451,  454,  456,  463,
        477,  479,  486,  493,  495,  499,  504,  505,  512,  515,  519,
        523,  529,  531,  533,  536,  537,  541,  550,  552,  557,  561,
        567,  570,  585,  593,  601,  602,  609,  619,  620,  623,  628,
        637,  639,  640,  651,  658,  659,  660,  666,  670,  672,  673,